export const ERROR_CODE = {
	GET_USER_DB: 'Unexpected database error, while getting user',
	CREATE_USER_UNHANDLED_ERROR: 'CREATE_USER_UNHANDLED_ERROR',
	USER_LOGIN_UNHANDLED_ERROR: 'USER_LOGIN_UNHANDLED_ERROR',
	USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
	REQUEST_NOT_ACCEPTABLE: 'REQUEST_NOT_ACCEPTABLE',
	CREATE_VALIDATION_UNHANDLED: 'CREATE_VALIDATION_UNHANDLED',
	CREATE_VALIDATION_ENTITY: 'CREATE_VALIDATION_ENTITY',
	UPDATE_VALIDATION_ENTITY: 'UPDATE_VALIDATION_ENTITY',
	UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
	INVALID_OTP: 'INVALID_OTP',
	INVALID_REFERRAL: 'INVALID_REFERRAL',
	EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
	PHONE_NOT_EXISTS: 'PHONE_NOT_EXISTS',
	INVALID_REQUEST_TYPE: 'INVALID_REQUEST_TYPE',
	NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',
	INVALID_PID: 'INVALID_PID',
	ENTITY_REQUIRED: 'ENTITY_REQUIRED',
	USER_NOT_EXISTS: 'USER_NOT_EXISTS',
};

export const DYNAMIC_REQUIRED = {
	USERNAME_LENGTH: 3,
	PASSWORD_LENGTH: 8,
};

export const ERROR_MESSAGE = {
	EMAIL_EXISTS: 'Email already exists',
	PHONE_EXISTS: 'Phone already exists',
	EMAIL_AND_USERNAME_EXISTS: 'Email and username already exists',
	PHONE_AND_USERNAME_EXISTS: 'Phone and username already exists',
	REQUEST_NOT_ACCEPTABLE: 'Unable to accept request',
	UNAUTHORIZED_ACCESS: `Username or password your are trying doesn't match`,
	INVALID_OTP: 'OTP is invalid or expired',
	INVALID_EMAIL: 'Invalid email',
	INVALID_PHONE: 'Invalid phone',
	USERNAME_LENGTH: `Username should have at least ${DYNAMIC_REQUIRED.USERNAME_LENGTH} characters`,
	PASSWORD_LENGTH: `Password should have at least ${DYNAMIC_REQUIRED.PASSWORD_LENGTH} characters`,
	NOT_ACCEPTABLE: 'Request not accpetable please contact on support',
	INVALID_PID: 'Invalid PID',
	USER_NOT_EXISTS: 'User not exists',
	PASSWORD_NOT_MATCHED: 'Invalid password',
	OLD_PASSWORD_NOT_MATCHED: 'Invalid old password',
};
