export type ValueOf<T> = T[keyof T];

export const USER_FLOW = {
	DASHBOARD: 'dashboard',
	EMAIL_VERIFICATION: 'email_verification',
	PHONE_VERIFICATION: 'phone_verification',
	KYC_PENDING: 'kyc_pending',
	DOCUMENT_VERIFICATION: 'document_verification',
	LIVENESS_VERIFICATION: 'liveness_verification',
	IN_VERIFICATION_PROCESS: 'in_verification_process',
};

export const COUNTRY: Record<
	string,
	{
		code: string;
		phoneCode: string;
		unicode: string;
		name: string;
		emoji: string;
	}
> = {
	AC: {
		code: 'AC',
		phoneCode: '+247',
		unicode: 'U+1F1E6 U+1F1E8',
		name: 'Ascension Island',
		emoji: '🇦🇨',
	},
	AD: {
		code: 'AD',
		phoneCode: '+376',
		unicode: 'U+1F1E6 U+1F1E9',
		name: 'Andorra',
		emoji: '🇦🇩',
	},
	AF: {
		code: 'AF',
		phoneCode: '+93',
		unicode: 'U+1F1E6 U+1F1EB',
		name: 'Afghanistan',
		emoji: '🇦🇫',
	},
	AG: {
		code: 'AG',
		phoneCode: '+1268',
		unicode: 'U+1F1E6 U+1F1EC',
		name: 'Antigua & Barbuda',
		emoji: '🇦🇬',
	},
	AI: {
		code: 'AI',
		phoneCode: '+1264',
		unicode: 'U+1F1E6 U+1F1EE',
		name: 'Anguilla',
		emoji: '🇦🇮',
	},
	AL: {
		code: 'AL',
		phoneCode: '+355',
		unicode: 'U+1F1E6 U+1F1F1',
		name: 'Albania',
		emoji: '🇦🇱',
	},
	AM: {
		code: 'AM',
		phoneCode: '+374',
		unicode: 'U+1F1E6 U+1F1F2',
		name: 'Armenia',
		emoji: '🇦🇲',
	},
	AO: {
		code: 'AO',
		phoneCode: '+244',
		unicode: 'U+1F1E6 U+1F1F4',
		name: 'Angola',
		emoji: '🇦🇴',
	},
	AQ: {
		code: 'AQ',
		phoneCode: '+672',
		unicode: 'U+1F1E6 U+1F1F6',
		name: 'Antarctica',
		emoji: '🇦🇶',
	},
	AR: {
		code: 'AR',
		phoneCode: '+54',
		unicode: 'U+1F1E6 U+1F1F7',
		name: 'Argentina',
		emoji: '🇦🇷',
	},
	AS: {
		code: 'AS',
		phoneCode: '+1684',
		unicode: 'U+1F1E6 U+1F1F8',
		name: 'American Samoa',
		emoji: '🇦🇸',
	},
	AT: {
		code: 'AT',
		phoneCode: '+43',
		unicode: 'U+1F1E6 U+1F1F9',
		name: 'Austria',
		emoji: '🇦🇹',
	},
	AU: {
		code: 'AU',
		phoneCode: '+61',
		unicode: 'U+1F1E6 U+1F1FA',
		name: 'Australia',
		emoji: '🇦🇺',
	},
	AW: {
		code: 'AW',
		phoneCode: '+297',
		unicode: 'U+1F1E6 U+1F1FC',
		name: 'Aruba',
		emoji: '🇦🇼',
	},
	AX: {
		code: 'AX',
		phoneCode: '+35818',
		unicode: 'U+1F1E6 U+1F1FD',
		name: 'Åland Islands',
		emoji: '🇦🇽',
	},
	AZ: {
		code: 'AZ',
		phoneCode: '+994',
		unicode: 'U+1F1E6 U+1F1FF',
		name: 'Azerbaijan',
		emoji: '🇦🇿',
	},
	BA: {
		code: 'BA',
		phoneCode: '+387',
		unicode: 'U+1F1E7 U+1F1E6',
		name: 'Bosnia & Herzegovina',
		emoji: '🇧🇦',
	},
	BB: {
		code: 'BB',
		phoneCode: '+1246',
		unicode: 'U+1F1E7 U+1F1E7',
		name: 'Barbados',
		emoji: '🇧🇧',
	},
	BD: {
		code: 'BD',
		phoneCode: '+880',
		unicode: 'U+1F1E7 U+1F1E9',
		name: 'Bangladesh',
		emoji: '🇧🇩',
	},
	BE: {
		code: 'BE',
		phoneCode: '+32',
		unicode: 'U+1F1E7 U+1F1EA',
		name: 'Belgium',
		emoji: '🇧🇪',
	},
	BF: {
		code: 'BF',
		phoneCode: '+226',
		unicode: 'U+1F1E7 U+1F1EB',
		name: 'Burkina Faso',
		emoji: '🇧🇫',
	},
	BG: {
		code: 'BG',
		phoneCode: '+359',
		unicode: 'U+1F1E7 U+1F1EC',
		name: 'Bulgaria',
		emoji: '🇧🇬',
	},
	BH: {
		code: 'BH',
		phoneCode: '+973',
		unicode: 'U+1F1E7 U+1F1ED',
		name: 'Bahrain',
		emoji: '🇧🇭',
	},
	BI: {
		code: 'BI',
		phoneCode: '+257',
		unicode: 'U+1F1E7 U+1F1EE',
		name: 'Burundi',
		emoji: '🇧🇮',
	},
	BJ: {
		code: 'BJ',
		phoneCode: '+229',
		unicode: 'U+1F1E7 U+1F1EF',
		name: 'Benin',
		emoji: '🇧🇯',
	},
	BL: {
		code: 'BL',
		phoneCode: '+590',
		unicode: 'U+1F1E7 U+1F1F1',
		name: 'St. Barthélemy',
		emoji: '🇧🇱',
	},
	BM: {
		code: 'BM',
		phoneCode: '+1441',
		unicode: 'U+1F1E7 U+1F1F2',
		name: 'Bermuda',
		emoji: '🇧🇲',
	},
	BN: {
		code: 'BN',
		phoneCode: '+673',
		unicode: 'U+1F1E7 U+1F1F3',
		name: 'Brunei',
		emoji: '🇧🇳',
	},
	BO: {
		code: 'BO',
		phoneCode: '+591',
		unicode: 'U+1F1E7 U+1F1F4',
		name: 'Bolivia',
		emoji: '🇧🇴',
	},
	BQ: {
		code: 'BQ',
		phoneCode: '+599',
		unicode: 'U+1F1E7 U+1F1F6',
		name: 'Caribbean Netherlands',
		emoji: '🇧🇶',
	},
	BR: {
		code: 'BR',
		phoneCode: '+55',
		unicode: 'U+1F1E7 U+1F1F7',
		name: 'Brazil',
		emoji: '🇧🇷',
	},
	BS: {
		code: 'BS',
		phoneCode: '+1242',
		unicode: 'U+1F1E7 U+1F1F8',
		name: 'Bahamas',
		emoji: '🇧🇸',
	},
	BT: {
		code: 'BT',
		phoneCode: '+975',
		unicode: 'U+1F1E7 U+1F1F9',
		name: 'Bhutan',
		emoji: '🇧🇹',
	},
	BV: {
		code: 'BV',
		phoneCode: '+47',
		unicode: 'U+1F1E7 U+1F1FB',
		name: 'Bouvet Island',
		emoji: '🇧🇻',
	},
	BW: {
		code: 'BW',
		phoneCode: '+267',
		unicode: 'U+1F1E7 U+1F1FC',
		name: 'Botswana',
		emoji: '🇧🇼',
	},
	BY: {
		code: 'BY',
		phoneCode: '+375',
		unicode: 'U+1F1E7 U+1F1FE',
		name: 'Belarus',
		emoji: '🇧🇾',
	},
	BZ: {
		code: 'BZ',
		phoneCode: '+501',
		unicode: 'U+1F1E7 U+1F1FF',
		name: 'Belize',
		emoji: '🇧🇿',
	},
	CA: {
		code: 'CA',
		phoneCode: '+1',
		unicode: 'U+1F1E8 U+1F1E6',
		name: 'Canada',
		emoji: '🇨🇦',
	},
	CC: {
		code: 'CC',
		phoneCode: '+61',
		unicode: 'U+1F1E8 U+1F1E8',
		name: 'Cocos (Keeling) Islands',
		emoji: '🇨🇨',
	},
	CD: {
		code: 'CD',
		phoneCode: '+243',
		unicode: 'U+1F1E8 U+1F1E9',
		name: 'Congo - Kinshasa',
		emoji: '🇨🇩',
	},
	CF: {
		code: 'CF',
		phoneCode: '+236',
		unicode: 'U+1F1E8 U+1F1EB',
		name: 'Central African Republic',
		emoji: '🇨🇫',
	},
	CG: {
		code: 'CG',
		phoneCode: '+242',
		unicode: 'U+1F1E8 U+1F1EC',
		name: 'Congo - Brazzaville',
		emoji: '🇨🇬',
	},
	CH: {
		code: 'CH',
		phoneCode: '+41',
		unicode: 'U+1F1E8 U+1F1ED',
		name: 'Switzerland',
		emoji: '🇨🇭',
	},
	CI: {
		code: 'CI',
		phoneCode: '+225',
		unicode: 'U+1F1E8 U+1F1EE',
		name: 'Côte d’Ivoire',
		emoji: '🇨🇮',
	},
	CK: {
		code: 'CK',
		phoneCode: '+682',
		unicode: 'U+1F1E8 U+1F1F0',
		name: 'Cook Islands',
		emoji: '🇨🇰',
	},
	CL: {
		code: 'CL',
		phoneCode: '+56',
		unicode: 'U+1F1E8 U+1F1F1',
		name: 'Chile',
		emoji: '🇨🇱',
	},
	CM: {
		code: 'CM',
		phoneCode: '+237',
		unicode: 'U+1F1E8 U+1F1F2',
		name: 'Cameroon',
		emoji: '🇨🇲',
	},
	CN: {
		code: 'CN',
		phoneCode: '+86',
		unicode: 'U+1F1E8 U+1F1F3',
		name: 'China',
		emoji: '🇨🇳',
	},
	CO: {
		code: 'CO',
		phoneCode: '+57',
		unicode: 'U+1F1E8 U+1F1F4',
		name: 'Colombia',
		emoji: '🇨🇴',
	},
	CP: {
		code: 'CP',
		phoneCode: '+262',
		unicode: 'U+1F1E8 U+1F1F5',
		name: 'Clipperton Island',
		emoji: '🇨🇵',
	},
	CR: {
		code: 'CR',
		phoneCode: '+506',
		unicode: 'U+1F1E8 U+1F1F7',
		name: 'Costa Rica',
		emoji: '🇨🇷',
	},
	CU: {
		code: 'CU',
		phoneCode: '+53',
		unicode: 'U+1F1E8 U+1F1FA',
		name: 'Cuba',
		emoji: '🇨🇺',
	},
	CV: {
		code: 'CV',
		phoneCode: '+238',
		unicode: 'U+1F1E8 U+1F1FB',
		name: 'Cape Verde',
		emoji: '🇨🇻',
	},
	CW: {
		code: 'CW',
		phoneCode: '+599',
		unicode: 'U+1F1E8 U+1F1FC',
		name: 'Curaçao',
		emoji: '🇨🇼',
	},
	CX: {
		code: 'CX',
		phoneCode: '+61',
		unicode: 'U+1F1E8 U+1F1FD',
		name: 'Christmas Island',
		emoji: '🇨🇽',
	},
	CY: {
		code: 'CY',
		phoneCode: '+357',
		unicode: 'U+1F1E8 U+1F1FE',
		name: 'Cyprus',
		emoji: '🇨🇾',
	},
	CZ: {
		code: 'CZ',
		phoneCode: '+420',
		unicode: 'U+1F1E8 U+1F1FF',
		name: 'Czechia',
		emoji: '🇨🇿',
	},
	DE: {
		code: 'DE',
		phoneCode: '+49',
		unicode: 'U+1F1E9 U+1F1EA',
		name: 'Germany',
		emoji: '🇩🇪',
	},
	DG: {
		code: 'DG',
		phoneCode: '+246',
		unicode: 'U+1F1E9 U+1F1EC',
		name: 'Diego Garcia',
		emoji: '🇩🇬',
	},
	DJ: {
		code: 'DJ',
		phoneCode: '+253',
		unicode: 'U+1F1E9 U+1F1EF',
		name: 'Djibouti',
		emoji: '🇩🇯',
	},
	DK: {
		code: 'DK',
		phoneCode: '+45',
		unicode: 'U+1F1E9 U+1F1F0',
		name: 'Denmark',
		emoji: '🇩🇰',
	},
	DM: {
		code: 'DM',
		phoneCode: '+1767',
		unicode: 'U+1F1E9 U+1F1F2',
		name: 'Dominica',
		emoji: '🇩🇲',
	},
	DO: {
		code: 'DO',
		phoneCode: '+1809',
		unicode: 'U+1F1E9 U+1F1F4',
		name: 'Dominican Republic',
		emoji: '🇩🇴',
	},
	DZ: {
		code: 'DZ',
		phoneCode: '+213',
		unicode: 'U+1F1E9 U+1F1FF',
		name: 'Algeria',
		emoji: '🇩🇿',
	},
	EA: {
		code: 'EA',
		phoneCode: '+34',
		unicode: 'U+1F1EA U+1F1E6',
		name: 'Ceuta & Melilla',
		emoji: '🇪🇦',
	},
	EC: {
		code: 'EC',
		phoneCode: '+593',
		unicode: 'U+1F1EA U+1F1E8',
		name: 'Ecuador',
		emoji: '🇪🇨',
	},
	EE: {
		code: 'EE',
		phoneCode: '+372',
		unicode: 'U+1F1EA U+1F1EA',
		name: 'Estonia',
		emoji: '🇪🇪',
	},
	EG: {
		code: 'EG',
		phoneCode: '+20',
		unicode: 'U+1F1EA U+1F1EC',
		name: 'Egypt',
		emoji: '🇪🇬',
	},
	EH: {
		code: 'EH',
		phoneCode: '+212',
		unicode: 'U+1F1EA U+1F1ED',
		name: 'Western Sahara',
		emoji: '🇪🇭',
	},
	ER: {
		code: 'ER',
		phoneCode: '+291',
		unicode: 'U+1F1EA U+1F1F7',
		name: 'Eritrea',
		emoji: '🇪🇷',
	},
	ES: {
		code: 'ES',
		phoneCode: '+34',
		unicode: 'U+1F1EA U+1F1F8',
		name: 'Spain',
		emoji: '🇪🇸',
	},
	ET: {
		code: 'ET',
		phoneCode: '+251',
		unicode: 'U+1F1EA U+1F1F9',
		name: 'Ethiopia',
		emoji: '🇪🇹',
	},
	EU: {
		code: 'EU',
		phoneCode: '00',
		unicode: 'U+1F1EA U+1F1FA',
		name: 'European Union',
		emoji: '🇪🇺',
	},
	FI: {
		code: 'FI',
		phoneCode: '+358',
		unicode: 'U+1F1EB U+1F1EE',
		name: 'Finland',
		emoji: '🇫🇮',
	},
	FJ: {
		code: 'FJ',
		phoneCode: '+679',
		unicode: 'U+1F1EB U+1F1EF',
		name: 'Fiji',
		emoji: '🇫🇯',
	},
	FK: {
		code: 'FK',
		phoneCode: '+500',
		unicode: 'U+1F1EB U+1F1F0',
		name: 'Falkland Islands',
		emoji: '🇫🇰',
	},
	FM: {
		code: 'FM',
		phoneCode: '+691',
		unicode: 'U+1F1EB U+1F1F2',
		name: 'Micronesia',
		emoji: '🇫🇲',
	},
	FO: {
		code: 'FO',
		phoneCode: '+298',
		unicode: 'U+1F1EB U+1F1F4',
		name: 'Faroe Islands',
		emoji: '🇫🇴',
	},
	FR: {
		code: 'FR',
		phoneCode: '+33',
		unicode: 'U+1F1EB U+1F1F7',
		name: 'France',
		emoji: '🇫🇷',
	},
	GA: {
		code: 'GA',
		phoneCode: '+241',
		unicode: 'U+1F1EC U+1F1E6',
		name: 'Gabon',
		emoji: '🇬🇦',
	},
	GD: {
		code: 'GD',
		phoneCode: '+1473',
		unicode: 'U+1F1EC U+1F1E9',
		name: 'Grenada',
		emoji: '🇬🇩',
	},
	GE: {
		code: 'GE',
		phoneCode: '+995',
		unicode: 'U+1F1EC U+1F1EA',
		name: 'Georgia',
		emoji: '🇬🇪',
	},
	GF: {
		code: 'GF',
		phoneCode: '+594',
		unicode: 'U+1F1EC U+1F1EB',
		name: 'French Guiana',
		emoji: '🇬🇫',
	},
	GG: {
		code: 'GG',
		phoneCode: '+441481',
		unicode: 'U+1F1EC U+1F1EC',
		name: 'Guernsey',
		emoji: '🇬🇬',
	},
	GH: {
		code: 'GH',
		phoneCode: '+233',
		unicode: 'U+1F1EC U+1F1ED',
		name: 'Ghana',
		emoji: '🇬🇭',
	},
	GI: {
		code: 'GI',
		phoneCode: '+350',
		unicode: 'U+1F1EC U+1F1EE',
		name: 'Gibraltar',
		emoji: '🇬🇮',
	},
	GL: {
		code: 'GL',
		phoneCode: '+299',
		unicode: 'U+1F1EC U+1F1F1',
		name: 'Greenland',
		emoji: '🇬🇱',
	},
	GM: {
		code: 'GM',
		phoneCode: '+220',
		unicode: 'U+1F1EC U+1F1F2',
		name: 'Gambia',
		emoji: '🇬🇲',
	},
	GN: {
		code: 'GN',
		phoneCode: '+224',
		unicode: 'U+1F1EC U+1F1F3',
		name: 'Guinea',
		emoji: '🇬🇳',
	},
	GP: {
		code: 'GP',
		phoneCode: '+590',
		unicode: 'U+1F1EC U+1F1F5',
		name: 'Guadeloupe',
		emoji: '🇬🇵',
	},
	GQ: {
		code: 'GQ',
		phoneCode: '+240',
		unicode: 'U+1F1EC U+1F1F6',
		name: 'Equatorial Guinea',
		emoji: '🇬🇶',
	},
	GR: {
		code: 'GR',
		phoneCode: '+30',
		unicode: 'U+1F1EC U+1F1F7',
		name: 'Greece',
		emoji: '🇬🇷',
	},
	GS: {
		code: 'GS',
		phoneCode: '+500',
		unicode: 'U+1F1EC U+1F1F8',
		name: 'South Georgia & South Sandwich Islands',
		emoji: '🇬🇸',
	},
	GT: {
		code: 'GT',
		phoneCode: '+502',
		unicode: 'U+1F1EC U+1F1F9',
		name: 'Guatemala',
		emoji: '🇬🇹',
	},
	GU: {
		code: 'GU',
		phoneCode: '+1671',
		unicode: 'U+1F1EC U+1F1FA',
		name: 'Guam',
		emoji: '🇬🇺',
	},
	GW: {
		code: 'GW',
		phoneCode: '+245',
		unicode: 'U+1F1EC U+1F1FC',
		name: 'Guinea-Bissau',
		emoji: '🇬🇼',
	},
	GY: {
		code: 'GY',
		phoneCode: '+592',
		unicode: 'U+1F1EC U+1F1FE',
		name: 'Guyana',
		emoji: '🇬🇾',
	},
	HK: {
		code: 'HK',
		phoneCode: '+852',
		unicode: 'U+1F1ED U+1F1F0',
		name: 'Hong Kong SAR China',
		emoji: '🇭🇰',
	},
	HM: {
		code: 'HM',
		phoneCode: '+672',
		unicode: 'U+1F1ED U+1F1F2',
		name: 'Heard & McDonald Islands',
		emoji: '🇭🇲',
	},
	HN: {
		code: 'HN',
		phoneCode: '+504',
		unicode: 'U+1F1ED U+1F1F3',
		name: 'Honduras',
		emoji: '🇭🇳',
	},
	HR: {
		code: 'HR',
		phoneCode: '+385',
		unicode: 'U+1F1ED U+1F1F7',
		name: 'Croatia',
		emoji: '🇭🇷',
	},
	HT: {
		code: 'HT',
		phoneCode: '+509',
		unicode: 'U+1F1ED U+1F1F9',
		name: 'Haiti',
		emoji: '🇭🇹',
	},
	HU: {
		code: 'HU',
		phoneCode: '+36',
		unicode: 'U+1F1ED U+1F1FA',
		name: 'Hungary',
		emoji: '🇭🇺',
	},
	IC: {
		code: 'IC',
		phoneCode: '+34',
		unicode: 'U+1F1EE U+1F1E8',
		name: 'Canary Islands',
		emoji: '🇮🇨',
	},
	ID: {
		code: 'ID',
		phoneCode: '+62',
		unicode: 'U+1F1EE U+1F1E9',
		name: 'Indonesia',
		emoji: '🇮🇩',
	},
	IE: {
		code: 'IE',
		phoneCode: '+353',
		unicode: 'U+1F1EE U+1F1EA',
		name: 'Ireland',
		emoji: '🇮🇪',
	},
	IL: {
		code: 'IL',
		phoneCode: '+972',
		unicode: 'U+1F1EE U+1F1F1',
		name: 'Israel',
		emoji: '🇮🇱',
	},
	IM: {
		code: 'IM',
		phoneCode: '+441624',
		unicode: 'U+1F1EE U+1F1F2',
		name: 'Isle of Man',
		emoji: '🇮🇲',
	},
	IN: {
		code: 'IN',
		phoneCode: '+91',
		unicode: 'U+1F1EE U+1F1F3',
		name: 'India',
		emoji: '🇮🇳',
	},
	IO: {
		code: 'IO',
		phoneCode: '+246',
		unicode: 'U+1F1EE U+1F1F4',
		name: 'British Indian Ocean Territory',
		emoji: '🇮🇴',
	},
	IQ: {
		code: 'IQ',
		phoneCode: '+964',
		unicode: 'U+1F1EE U+1F1F6',
		name: 'Iraq',
		emoji: '🇮🇶',
	},
	IR: {
		code: 'IR',
		phoneCode: '+98',
		unicode: 'U+1F1EE U+1F1F7',
		name: 'Iran',
		emoji: '🇮🇷',
	},
	IS: {
		code: 'IS',
		phoneCode: '+354',
		unicode: 'U+1F1EE U+1F1F8',
		name: 'Iceland',
		emoji: '🇮🇸',
	},
	IT: {
		code: 'IT',
		phoneCode: '+39',
		unicode: 'U+1F1EE U+1F1F9',
		name: 'Italy',
		emoji: '🇮🇹',
	},
	JE: {
		code: 'JE',
		phoneCode: '+441534',
		unicode: 'U+1F1EF U+1F1EA',
		name: 'Jersey',
		emoji: '🇯🇪',
	},
	JM: {
		code: 'JM',
		phoneCode: '+1876',
		unicode: 'U+1F1EF U+1F1F2',
		name: 'Jamaica',
		emoji: '🇯🇲',
	},
	JO: {
		code: 'JO',
		phoneCode: '+962',
		unicode: 'U+1F1EF U+1F1F4',
		name: 'Jordan',
		emoji: '🇯🇴',
	},
	JP: {
		code: 'JP',
		phoneCode: '+81',
		unicode: 'U+1F1EF U+1F1F5',
		name: 'Japan',
		emoji: '🇯🇵',
	},
	KE: {
		code: 'KE',
		phoneCode: '+254',
		unicode: 'U+1F1F0 U+1F1EA',
		name: 'Kenya',
		emoji: '🇰🇪',
	},
	KG: {
		code: 'KG',
		phoneCode: '+996',
		unicode: 'U+1F1F0 U+1F1EC',
		name: 'Kyrgyzstan',
		emoji: '🇰🇬',
	},
	KH: {
		code: 'KH',
		phoneCode: '+855',
		unicode: 'U+1F1F0 U+1F1ED',
		name: 'Cambodia',
		emoji: '🇰🇭',
	},
	KI: {
		code: 'KI',
		phoneCode: '+686',
		unicode: 'U+1F1F0 U+1F1EE',
		name: 'Kiribati',
		emoji: '🇰🇮',
	},
	KM: {
		code: 'KM',
		phoneCode: '+269',
		unicode: 'U+1F1F0 U+1F1F2',
		name: 'Comoros',
		emoji: '🇰🇲',
	},
	KN: {
		code: 'KN',
		phoneCode: '+1869',
		unicode: 'U+1F1F0 U+1F1F3',
		name: 'St. Kitts & Nevis',
		emoji: '🇰🇳',
	},
	KP: {
		code: 'KP',
		phoneCode: '+850',
		unicode: 'U+1F1F0 U+1F1F5',
		name: 'North Korea',
		emoji: '🇰🇵',
	},
	KR: {
		code: 'KR',
		phoneCode: '+82',
		unicode: 'U+1F1F0 U+1F1F7',
		name: 'South Korea',
		emoji: '🇰🇷',
	},
	KW: {
		code: 'KW',
		phoneCode: '+965',
		unicode: 'U+1F1F0 U+1F1FC',
		name: 'Kuwait',
		emoji: '🇰🇼',
	},
	KY: {
		code: 'KY',
		phoneCode: '+1345',
		unicode: 'U+1F1F0 U+1F1FE',
		name: 'Cayman Islands',
		emoji: '🇰🇾',
	},
	KZ: {
		code: 'KZ',
		phoneCode: '+7',
		unicode: 'U+1F1F0 U+1F1FF',
		name: 'Kazakhstan',
		emoji: '🇰🇿',
	},
	LA: {
		code: 'LA',
		phoneCode: '+856',
		unicode: 'U+1F1F1 U+1F1E6',
		name: 'Laos',
		emoji: '🇱🇦',
	},
	LB: {
		code: 'LB',
		phoneCode: '+961',
		unicode: 'U+1F1F1 U+1F1E7',
		name: 'Lebanon',
		emoji: '🇱🇧',
	},
	LC: {
		code: 'LC',
		phoneCode: '+1758',
		unicode: 'U+1F1F1 U+1F1E8',
		name: 'St. Lucia',
		emoji: '🇱🇨',
	},
	LI: {
		code: 'LI',
		phoneCode: '+423',
		unicode: 'U+1F1F1 U+1F1EE',
		name: 'Liechtenstein',
		emoji: '🇱🇮',
	},
	LK: {
		code: 'LK',
		phoneCode: '+94',
		unicode: 'U+1F1F1 U+1F1F0',
		name: 'Sri Lanka',
		emoji: '🇱🇰',
	},
	LR: {
		code: 'LR',
		phoneCode: '+231',
		unicode: 'U+1F1F1 U+1F1F7',
		name: 'Liberia',
		emoji: '🇱🇷',
	},
	LS: {
		code: 'LS',
		phoneCode: '+266',
		unicode: 'U+1F1F1 U+1F1F8',
		name: 'Lesotho',
		emoji: '🇱🇸',
	},
	LT: {
		code: 'LT',
		phoneCode: '+370',
		unicode: 'U+1F1F1 U+1F1F9',
		name: 'Lithuania',
		emoji: '🇱🇹',
	},
	LU: {
		code: 'LU',
		phoneCode: '+352',
		unicode: 'U+1F1F1 U+1F1FA',
		name: 'Luxembourg',
		emoji: '🇱🇺',
	},
	LV: {
		code: 'LV',
		phoneCode: '+371',
		unicode: 'U+1F1F1 U+1F1FB',
		name: 'Latvia',
		emoji: '🇱🇻',
	},
	LY: {
		code: 'LY',
		phoneCode: '+218',
		unicode: 'U+1F1F1 U+1F1FE',
		name: 'Libya',
		emoji: '🇱🇾',
	},
	MA: {
		code: 'MA',
		phoneCode: '+212',
		unicode: 'U+1F1F2 U+1F1E6',
		name: 'Morocco',
		emoji: '🇲🇦',
	},
	MC: {
		code: 'MC',
		phoneCode: '+377',
		unicode: 'U+1F1F2 U+1F1E8',
		name: 'Monaco',
		emoji: '🇲🇨',
	},
	MD: {
		code: 'MD',
		phoneCode: '+373',
		unicode: 'U+1F1F2 U+1F1E9',
		name: 'Moldova',
		emoji: '🇲🇩',
	},
	ME: {
		code: 'ME',
		phoneCode: '+382',
		unicode: 'U+1F1F2 U+1F1EA',
		name: 'Montenegro',
		emoji: '🇲🇪',
	},
	MF: {
		code: 'MF',
		phoneCode: '+590',
		unicode: 'U+1F1F2 U+1F1EB',
		name: 'St. Martin',
		emoji: '🇲🇫',
	},
	MG: {
		code: 'MG',
		phoneCode: '+261',
		unicode: 'U+1F1F2 U+1F1EC',
		name: 'Madagascar',
		emoji: '🇲🇬',
	},
	MH: {
		code: 'MH',
		phoneCode: '+692',
		unicode: 'U+1F1F2 U+1F1ED',
		name: 'Marshall Islands',
		emoji: '🇲🇭',
	},
	MK: {
		code: 'MK',
		phoneCode: '+389',
		unicode: 'U+1F1F2 U+1F1F0',
		name: 'Macedonia',
		emoji: '🇲🇰',
	},
	ML: {
		code: 'ML',
		phoneCode: '+223',
		unicode: 'U+1F1F2 U+1F1F1',
		name: 'Mali',
		emoji: '🇲🇱',
	},
	MM: {
		code: 'MM',
		phoneCode: '+95',
		unicode: 'U+1F1F2 U+1F1F2',
		name: 'Myanmar (Burma)',
		emoji: '🇲🇲',
	},
	MN: {
		code: 'MN',
		phoneCode: '+976',
		unicode: 'U+1F1F2 U+1F1F3',
		name: 'Mongolia',
		emoji: '🇲🇳',
	},
	MO: {
		code: 'MO',
		phoneCode: '+853',
		unicode: 'U+1F1F2 U+1F1F4',
		name: 'Macau SAR China',
		emoji: '🇲🇴',
	},
	MP: {
		code: 'MP',
		phoneCode: '+1670',
		unicode: 'U+1F1F2 U+1F1F5',
		name: 'Northern Mariana Islands',
		emoji: '🇲🇵',
	},
	MQ: {
		code: 'MQ',
		phoneCode: '+596',
		unicode: 'U+1F1F2 U+1F1F6',
		name: 'Martinique',
		emoji: '🇲🇶',
	},
	MR: {
		code: 'MR',
		phoneCode: '+222',
		unicode: 'U+1F1F2 U+1F1F7',
		name: 'Mauritania',
		emoji: '🇲🇷',
	},
	MS: {
		code: 'MS',
		phoneCode: '+1664',
		unicode: 'U+1F1F2 U+1F1F8',
		name: 'Montserrat',
		emoji: '🇲🇸',
	},
	MT: {
		code: 'MT',
		phoneCode: '+356',
		unicode: 'U+1F1F2 U+1F1F9',
		name: 'Malta',
		emoji: '🇲🇹',
	},
	MU: {
		code: 'MU',
		phoneCode: '+230',
		unicode: 'U+1F1F2 U+1F1FA',
		name: 'Mauritius',
		emoji: '🇲🇺',
	},
	MV: {
		code: 'MV',
		phoneCode: '+960',
		unicode: 'U+1F1F2 U+1F1FB',
		name: 'Maldives',
		emoji: '🇲🇻',
	},
	MW: {
		code: 'MW',
		phoneCode: '+265',
		unicode: 'U+1F1F2 U+1F1FC',
		name: 'Malawi',
		emoji: '🇲🇼',
	},
	MX: {
		code: 'MX',
		phoneCode: '+52',
		unicode: 'U+1F1F2 U+1F1FD',
		name: 'Mexico',
		emoji: '🇲🇽',
	},
	MY: {
		code: 'MY',
		phoneCode: '+60',
		unicode: 'U+1F1F2 U+1F1FE',
		name: 'Malaysia',
		emoji: '🇲🇾',
	},
	MZ: {
		code: 'MZ',
		phoneCode: '+258',
		unicode: 'U+1F1F2 U+1F1FF',
		name: 'Mozambique',
		emoji: '🇲🇿',
	},
	NA: {
		code: 'NA',
		phoneCode: '+264',
		unicode: 'U+1F1F3 U+1F1E6',
		name: 'Namibia',
		emoji: '🇳🇦',
	},
	NC: {
		code: 'NC',
		phoneCode: '+687',
		unicode: 'U+1F1F3 U+1F1E8',
		name: 'New Caledonia',
		emoji: '🇳🇨',
	},
	NE: {
		code: 'NE',
		phoneCode: '+227',
		unicode: 'U+1F1F3 U+1F1EA',
		name: 'Niger',
		emoji: '🇳🇪',
	},
	NF: {
		code: 'NF',
		phoneCode: '+672',
		unicode: 'U+1F1F3 U+1F1EB',
		name: 'Norfolk Island',
		emoji: '🇳🇫',
	},
	NG: {
		code: 'NG',
		phoneCode: '+234',
		unicode: 'U+1F1F3 U+1F1EC',
		name: 'Nigeria',
		emoji: '🇳🇬',
	},
	NI: {
		code: 'NI',
		phoneCode: '+505',
		unicode: 'U+1F1F3 U+1F1EE',
		name: 'Nicaragua',
		emoji: '🇳🇮',
	},
	NL: {
		code: 'NL',
		phoneCode: '+31',
		unicode: 'U+1F1F3 U+1F1F1',
		name: 'Netherlands',
		emoji: '🇳🇱',
	},
	NO: {
		code: 'NO',
		phoneCode: '+47',
		unicode: 'U+1F1F3 U+1F1F4',
		name: 'Norway',
		emoji: '🇳🇴',
	},
	NP: {
		code: 'NP',
		phoneCode: '+977',
		unicode: 'U+1F1F3 U+1F1F5',
		name: 'Nepal',
		emoji: '🇳🇵',
	},
	NR: {
		code: 'NR',
		phoneCode: '+674',
		unicode: 'U+1F1F3 U+1F1F7',
		name: 'Nauru',
		emoji: '🇳🇷',
	},
	NU: {
		code: 'NU',
		phoneCode: '+683',
		unicode: 'U+1F1F3 U+1F1FA',
		name: 'Niue',
		emoji: '🇳🇺',
	},
	NZ: {
		code: 'NZ',
		phoneCode: '+64',
		unicode: 'U+1F1F3 U+1F1FF',
		name: 'New Zealand',
		emoji: '🇳🇿',
	},
	OM: {
		code: 'OM',
		phoneCode: '+968',
		unicode: 'U+1F1F4 U+1F1F2',
		name: 'Oman',
		emoji: '🇴🇲',
	},
	PA: {
		code: 'PA',
		phoneCode: '+507',
		unicode: 'U+1F1F5 U+1F1E6',
		name: 'Panama',
		emoji: '🇵🇦',
	},
	PE: {
		code: 'PE',
		phoneCode: '+51',
		unicode: 'U+1F1F5 U+1F1EA',
		name: 'Peru',
		emoji: '🇵🇪',
	},
	PF: {
		code: 'PF',
		phoneCode: '+689',
		unicode: 'U+1F1F5 U+1F1EB',
		name: 'French Polynesia',
		emoji: '🇵🇫',
	},
	PG: {
		code: 'PG',
		phoneCode: '+675',
		unicode: 'U+1F1F5 U+1F1EC',
		name: 'Papua New Guinea',
		emoji: '🇵🇬',
	},
	PH: {
		code: 'PH',
		phoneCode: '+63',
		unicode: 'U+1F1F5 U+1F1ED',
		name: 'Philippines',
		emoji: '🇵🇭',
	},
	PK: {
		code: 'PK',
		phoneCode: '+92',
		unicode: 'U+1F1F5 U+1F1F0',
		name: 'Pakistan',
		emoji: '🇵🇰',
	},
	PL: {
		code: 'PL',
		phoneCode: '+48',
		unicode: 'U+1F1F5 U+1F1F1',
		name: 'Poland',
		emoji: '🇵🇱',
	},
	PM: {
		code: 'PM',
		phoneCode: '+508',
		unicode: 'U+1F1F5 U+1F1F2',
		name: 'St. Pierre & Miquelon',
		emoji: '🇵🇲',
	},
	PN: {
		code: 'PN',
		phoneCode: '+64',
		unicode: 'U+1F1F5 U+1F1F3',
		name: 'Pitcairn Islands',
		emoji: '🇵🇳',
	},
	PR: {
		code: 'PR',
		phoneCode: '+1787',
		unicode: 'U+1F1F5 U+1F1F7',
		name: 'Puerto Rico',
		emoji: '🇵🇷',
	},
	PS: {
		code: 'PS',
		phoneCode: '+970',
		unicode: 'U+1F1F5 U+1F1F8',
		name: 'Palestinian Territories',
		emoji: '🇵🇸',
	},
	PT: {
		code: 'PT',
		phoneCode: '+351',
		unicode: 'U+1F1F5 U+1F1F9',
		name: 'Portugal',
		emoji: '🇵🇹',
	},
	PW: {
		code: 'PW',
		phoneCode: '+680',
		unicode: 'U+1F1F5 U+1F1FC',
		name: 'Palau',
		emoji: '🇵🇼',
	},
	PY: {
		code: 'PY',
		phoneCode: '+595',
		unicode: 'U+1F1F5 U+1F1FE',
		name: 'Paraguay',
		emoji: '🇵🇾',
	},
	QA: {
		code: 'QA',
		phoneCode: '+974',
		unicode: 'U+1F1F6 U+1F1E6',
		name: 'Qatar',
		emoji: '🇶🇦',
	},
	RE: {
		code: 'RE',
		phoneCode: '+262',
		unicode: 'U+1F1F7 U+1F1EA',
		name: 'Réunion',
		emoji: '🇷🇪',
	},
	RO: {
		code: 'RO',
		phoneCode: '+40',
		unicode: 'U+1F1F7 U+1F1F4',
		name: 'Romania',
		emoji: '🇷🇴',
	},
	RS: {
		code: 'RS',
		phoneCode: '+381',
		unicode: 'U+1F1F7 U+1F1F8',
		name: 'Serbia',
		emoji: '🇷🇸',
	},
	RU: {
		code: 'RU',
		phoneCode: '+7',
		unicode: 'U+1F1F7 U+1F1FA',
		name: 'Russia',
		emoji: '🇷🇺',
	},
	RW: {
		code: 'RW',
		phoneCode: '+250',
		unicode: 'U+1F1F7 U+1F1FC',
		name: 'Rwanda',
		emoji: '🇷🇼',
	},
	SA: {
		code: 'SA',
		phoneCode: '+966',
		unicode: 'U+1F1F8 U+1F1E6',
		name: 'Saudi Arabia',
		emoji: '🇸🇦',
	},
	SB: {
		code: 'SB',
		phoneCode: '+677',
		unicode: 'U+1F1F8 U+1F1E7',
		name: 'Solomon Islands',
		emoji: '🇸🇧',
	},
	SC: {
		code: 'SC',
		phoneCode: '+248',
		unicode: 'U+1F1F8 U+1F1E8',
		name: 'Seychelles',
		emoji: '🇸🇨',
	},
	SD: {
		code: 'SD',
		phoneCode: '+249',
		unicode: 'U+1F1F8 U+1F1E9',
		name: 'Sudan',
		emoji: '🇸🇩',
	},
	SE: {
		code: 'SE',
		phoneCode: '+46',
		unicode: 'U+1F1F8 U+1F1EA',
		name: 'Sweden',
		emoji: '🇸🇪',
	},
	SG: {
		code: 'SG',
		phoneCode: '+65',
		unicode: 'U+1F1F8 U+1F1EC',
		name: 'Singapore',
		emoji: '🇸🇬',
	},
	SH: {
		code: 'SH',
		phoneCode: '+290',
		unicode: 'U+1F1F8 U+1F1ED',
		name: 'St. Helena',
		emoji: '🇸🇭',
	},
	SI: {
		code: 'SI',
		phoneCode: '+386',
		unicode: 'U+1F1F8 U+1F1EE',
		name: 'Slovenia',
		emoji: '🇸🇮',
	},
	SJ: {
		code: 'SJ',
		phoneCode: '+47',
		unicode: 'U+1F1F8 U+1F1EF',
		name: 'Svalbard & Jan Mayen',
		emoji: '🇸🇯',
	},
	SK: {
		code: 'SK',
		phoneCode: '+421',
		unicode: 'U+1F1F8 U+1F1F0',
		name: 'Slovakia',
		emoji: '🇸🇰',
	},
	SL: {
		code: 'SL',
		phoneCode: '+232',
		unicode: 'U+1F1F8 U+1F1F1',
		name: 'Sierra Leone',
		emoji: '🇸🇱',
	},
	SM: {
		code: 'SM',
		phoneCode: '+378',
		unicode: 'U+1F1F8 U+1F1F2',
		name: 'San Marino',
		emoji: '🇸🇲',
	},
	SN: {
		code: 'SN',
		phoneCode: '+221',
		unicode: 'U+1F1F8 U+1F1F3',
		name: 'Senegal',
		emoji: '🇸🇳',
	},
	SO: {
		code: 'SO',
		phoneCode: '+252',
		unicode: 'U+1F1F8 U+1F1F4',
		name: 'Somalia',
		emoji: '🇸🇴',
	},
	SR: {
		code: 'SR',
		phoneCode: '+597',
		unicode: 'U+1F1F8 U+1F1F7',
		name: 'Suriname',
		emoji: '🇸🇷',
	},
	SS: {
		code: 'SS',
		phoneCode: '+211',
		unicode: 'U+1F1F8 U+1F1F8',
		name: 'South Sudan',
		emoji: '🇸🇸',
	},
	ST: {
		code: 'ST',
		phoneCode: '+239',
		unicode: 'U+1F1F8 U+1F1F9',
		name: 'São Tomé & Príncipe',
		emoji: '🇸🇹',
	},
	SV: {
		code: 'SV',
		phoneCode: '+503',
		unicode: 'U+1F1F8 U+1F1FB',
		name: 'El Salvador',
		emoji: '🇸🇻',
	},
	SX: {
		code: 'SX',
		phoneCode: '+1721',
		unicode: 'U+1F1F8 U+1F1FD',
		name: 'Sint Maarten',
		emoji: '🇸🇽',
	},
	SY: {
		code: 'SY',
		phoneCode: '+963',
		unicode: 'U+1F1F8 U+1F1FE',
		name: 'Syria',
		emoji: '🇸🇾',
	},
	SZ: {
		code: 'SZ',
		phoneCode: '+268',
		unicode: 'U+1F1F8 U+1F1FF',
		name: 'Swaziland',
		emoji: '🇸🇿',
	},
	TA: {
		code: 'TA',
		phoneCode: '+290',
		unicode: 'U+1F1F9 U+1F1E6',
		name: 'Tristan da Cunha',
		emoji: '🇹🇦',
	},
	TC: {
		code: 'TC',
		phoneCode: '+1649',
		unicode: 'U+1F1F9 U+1F1E8',
		name: 'Turks & Caicos Islands',
		emoji: '🇹🇨',
	},
	TD: {
		code: 'TD',
		phoneCode: '+235',
		unicode: 'U+1F1F9 U+1F1E9',
		name: 'Chad',
		emoji: '🇹🇩',
	},
	TF: {
		code: 'TF',
		phoneCode: '+262',
		unicode: 'U+1F1F9 U+1F1EB',
		name: 'French Southern Territories',
		emoji: '🇹🇫',
	},
	TG: {
		code: 'TG',
		phoneCode: '+228',
		unicode: 'U+1F1F9 U+1F1EC',
		name: 'Togo',
		emoji: '🇹🇬',
	},
	TH: {
		code: 'TH',
		phoneCode: '+66',
		unicode: 'U+1F1F9 U+1F1ED',
		name: 'Thailand',
		emoji: '🇹🇭',
	},
	TJ: {
		code: 'TJ',
		phoneCode: '+992',
		unicode: 'U+1F1F9 U+1F1EF',
		name: 'Tajikistan',
		emoji: '🇹🇯',
	},
	TK: {
		code: 'TK',
		phoneCode: '+690',
		unicode: 'U+1F1F9 U+1F1F0',
		name: 'Tokelau',
		emoji: '🇹🇰',
	},
	TL: {
		code: 'TL',
		phoneCode: '+670',
		unicode: 'U+1F1F9 U+1F1F1',
		name: 'Timor-Leste',
		emoji: '🇹🇱',
	},
	TM: {
		code: 'TM',
		phoneCode: '+993',
		unicode: 'U+1F1F9 U+1F1F2',
		name: 'Turkmenistan',
		emoji: '🇹🇲',
	},
	TN: {
		code: 'TN',
		phoneCode: '+216',
		unicode: 'U+1F1F9 U+1F1F3',
		name: 'Tunisia',
		emoji: '🇹🇳',
	},
	TO: {
		code: 'TO',
		phoneCode: '+676',
		unicode: 'U+1F1F9 U+1F1F4',
		name: 'Tonga',
		emoji: '🇹🇴',
	},
	TR: {
		code: 'TR',
		phoneCode: '+90',
		unicode: 'U+1F1F9 U+1F1F7',
		name: 'Turkey',
		emoji: '🇹🇷',
	},
	TT: {
		code: 'TT',
		phoneCode: '+1868',
		unicode: 'U+1F1F9 U+1F1F9',
		name: 'Trinidad & Tobago',
		emoji: '🇹🇹',
	},
	TV: {
		code: 'TV',
		phoneCode: '+688',
		unicode: 'U+1F1F9 U+1F1FB',
		name: 'Tuvalu',
		emoji: '🇹🇻',
	},
	TW: {
		code: 'TW',
		phoneCode: '+886',
		unicode: 'U+1F1F9 U+1F1FC',
		name: 'Taiwan',
		emoji: '🇹🇼',
	},
	TZ: {
		code: 'TZ',
		phoneCode: '+255',
		unicode: 'U+1F1F9 U+1F1FF',
		name: 'Tanzania',
		emoji: '🇹🇿',
	},
	UA: {
		code: 'UA',
		phoneCode: '+380',
		unicode: 'U+1F1FA U+1F1E6',
		name: 'Ukraine',
		emoji: '🇺🇦',
	},
	UG: {
		code: 'UG',
		phoneCode: '+256',
		unicode: 'U+1F1FA U+1F1EC',
		name: 'Uganda',
		emoji: '🇺🇬',
	},
	UM: {
		code: 'UM',
		phoneCode: '+1',
		unicode: 'U+1F1FA U+1F1F2',
		name: 'U.S. Outlying Islands',
		emoji: '🇺🇲',
	},
	UN: {
		code: 'UN',
		phoneCode: '+1',
		unicode: 'U+1F1FA U+1F1F3',
		name: 'United Nations',
		emoji: '🇺🇳',
	},
	UY: {
		code: 'UY',
		phoneCode: '+598',
		unicode: 'U+1F1FA U+1F1FE',
		name: 'Uruguay',
		emoji: '🇺🇾',
	},
	UZ: {
		code: 'UZ',
		phoneCode: '+998',
		unicode: 'U+1F1FA U+1F1FF',
		name: 'Uzbekistan',
		emoji: '🇺🇿',
	},
	VA: {
		code: 'VA',
		phoneCode: '+379',
		unicode: 'U+1F1FB U+1F1E6',
		name: 'Vatican City',
		emoji: '🇻🇦',
	},
	VC: {
		code: 'VC',
		phoneCode: '+1784',
		unicode: 'U+1F1FB U+1F1E8',
		name: 'St. Vincent & Grenadines',
		emoji: '🇻🇨',
	},
	VE: {
		code: 'VE',
		phoneCode: '+58',
		unicode: 'U+1F1FB U+1F1EA',
		name: 'Venezuela',
		emoji: '🇻🇪',
	},
	VG: {
		code: 'VG',
		phoneCode: '+1284',
		unicode: 'U+1F1FB U+1F1EC',
		name: 'British Virgin Islands',
		emoji: '🇻🇬',
	},
	VI: {
		code: 'VI',
		phoneCode: '+1340',
		unicode: 'U+1F1FB U+1F1EE',
		name: 'U.S. Virgin Islands',
		emoji: '🇻🇮',
	},
	VN: {
		code: 'VN',
		phoneCode: '+84',
		unicode: 'U+1F1FB U+1F1F3',
		name: 'Vietnam',
		emoji: '🇻🇳',
	},
	VU: {
		code: 'VU',
		phoneCode: '+678',
		unicode: 'U+1F1FB U+1F1FA',
		name: 'Vanuatu',
		emoji: '🇻🇺',
	},
	WF: {
		code: 'WF',
		phoneCode: '+681',
		unicode: 'U+1F1FC U+1F1EB',
		name: 'Wallis & Futuna',
		emoji: '🇼🇫',
	},
	WS: {
		code: 'WS',
		phoneCode: '+685',
		unicode: 'U+1F1FC U+1F1F8',
		name: 'Samoa',
		emoji: '🇼🇸',
	},
	XK: {
		code: 'XK',
		phoneCode: '+383',
		unicode: 'U+1F1FD U+1F1F0',
		name: 'Kosovo',
		emoji: '🇽🇰',
	},
	YE: {
		code: 'YE',
		phoneCode: '+967',
		unicode: 'U+1F1FE U+1F1EA',
		name: 'Yemen',
		emoji: '🇾🇪',
	},
	YT: {
		code: 'YT',
		phoneCode: '+262',
		unicode: 'U+1F1FE U+1F1F9',
		name: 'Mayotte',
		emoji: '🇾🇹',
	},
	ZA: {
		code: 'ZA',
		phoneCode: '+27',
		unicode: 'U+1F1FF U+1F1E6',
		name: 'South Africa',
		emoji: '🇿🇦',
	},
	ZM: {
		code: 'ZM',
		phoneCode: '+260',
		unicode: 'U+1F1FF U+1F1F2',
		name: 'Zambia',
		emoji: '🇿🇲',
	},
	ZW: {
		code: 'ZW',
		phoneCode: '+263',
		unicode: 'U+1F1FF U+1F1FC',
		name: 'Zimbabwe',
		emoji: '🇿🇼',
	},
};

export const COMPONENT_NAME = {
	ADMIN: 'admin',
	USER: 'user',
	CONFIG: 'config',
	SETURA: 'setura',
};

export const VALID_USER_QUERY = {
	isArchived: false,
};

export const VALID_ADMIN_USER_QUERY = {
	isArchived: false,
};

export enum ROLE_NAME {
	ADMIN = 'admin',
	REVIEWER = 'reviewer',
	SUPER_ADMIN = 'super_admin',
	SUPPORT = 'support',
}

export const MODULE_NAME = {
	DASHBOARD: 'dashboard',
	USER: 'user',
	ADMIN_USER: 'admin_user',
	SUPPORT: 'support',
};

export const PERMISSION_TYPES = {
	ALL: 'all',
	EDIT: 'edit',
	DELETE: 'delete',
	VIEW: 'view',
};

export const ROLE_PERMISSIONS = {
	[ROLE_NAME.ADMIN]: {
		[MODULE_NAME.DASHBOARD]: {
			view: true,
			edit: true,
			delete: true,
		},
		[MODULE_NAME.USER]: {
			view: true,
			edit: true,
			delete: true,
		},
		[MODULE_NAME.ADMIN_USER]: {
			view: true,
			edit: true,
			delete: true,
		},
		[MODULE_NAME.SUPPORT]: {
			view: true,
			edit: true,
			delete: true,
		},
	},
	[ROLE_NAME.REVIEWER]: {
		[MODULE_NAME.DASHBOARD]: {
			view: true,
			edit: false,
			delete: false,
		},
		[MODULE_NAME.USER]: {
			view: true,
			edit: false,
			delete: false,
		},
		[MODULE_NAME.ADMIN_USER]: {
			view: false,
			edit: false,
			delete: false,
		},
		[MODULE_NAME.SUPPORT]: {
			view: true,
			edit: false,
			delete: false,
		},
	},
	[ROLE_NAME.SUPPORT]: {
		[MODULE_NAME.DASHBOARD]: {
			view: true,
			edit: false,
			delete: false,
		},
		[MODULE_NAME.USER]: {
			view: true,
			edit: true,
			delete: false,
		},
		[MODULE_NAME.ADMIN_USER]: {
			view: false,
			edit: false,
			delete: false,
		},
		[MODULE_NAME.SUPPORT]: {
			view: true,
			edit: true,
			delete: true,
		},
	},
};

export const PAGINATE_RECORD_TYPE_DEFINATION = {
	docs: 'any',
	totalDocs: 'string',
	totalPages: 'string',
	data: 'any',
	total: 'string',
	limit: 'string',
	pages: 'string',
	page: 'string',
};

export const TIMEZONE = [
	'Africa/Abidjan',
	'Africa/Accra',
	'Africa/Addis_Ababa',
	'Africa/Algiers',
	'Africa/Asmara',
	'Africa/Asmera',
	'Africa/Bamako',
	'Africa/Bangui',
	'Africa/Banjul',
	'Africa/Bissau',
	'Africa/Blantyre',
	'Africa/Brazzaville',
	'Africa/Bujumbura',
	'Africa/Cairo',
	'Africa/Casablanca',
	'Africa/Ceuta',
	'Africa/Conakry',
	'Africa/Dakar',
	'Africa/Dar_es_Salaam',
	'Africa/Djibouti',
	'Africa/Douala',
	'Africa/El_Aaiun',
	'Africa/Freetown',
	'Africa/Gaborone',
	'Africa/Harare',
	'Africa/Johannesburg',
	'Africa/Juba',
	'Africa/Kampala',
	'Africa/Khartoum',
	'Africa/Kigali',
	'Africa/Kinshasa',
	'Africa/Lagos',
	'Africa/Libreville',
	'Africa/Lome',
	'Africa/Luanda',
	'Africa/Lubumbashi',
	'Africa/Lusaka',
	'Africa/Malabo',
	'Africa/Maputo',
	'Africa/Maseru',
	'Africa/Mbabane',
	'Africa/Mogadishu',
	'Africa/Monrovia',
	'Africa/Nairobi',
	'Africa/Ndjamena',
	'Africa/Niamey',
	'Africa/Nouakchott',
	'Africa/Ouagadougou',
	'Africa/Porto-Novo',
	'Africa/Sao_Tome',
	'Africa/Timbuktu',
	'Africa/Tripoli',
	'Africa/Tunis',
	'Africa/Windhoek',
	'America/Adak',
	'America/Anchorage',
	'America/Anguilla',
	'America/Antigua',
	'America/Araguaina',
	'America/Argentina/Buenos_Aires',
	'America/Argentina/Catamarca',
	'America/Argentina/ComodRivadavia',
	'America/Argentina/Cordoba',
	'America/Argentina/Jujuy',
	'America/Argentina/La_Rioja',
	'America/Argentina/Mendoza',
	'America/Argentina/Rio_Gallegos',
	'America/Argentina/Salta',
	'America/Argentina/San_Juan',
	'America/Argentina/San_Luis',
	'America/Argentina/Tucuman',
	'America/Argentina/Ushuaia',
	'America/Aruba',
	'America/Asuncion',
	'America/Atikokan',
	'America/Atka',
	'America/Bahia',
	'America/Bahia_Banderas',
	'America/Barbados',
	'America/Belem',
	'America/Belize',
	'America/Blanc-Sablon',
	'America/Boa_Vista',
	'America/Bogota',
	'America/Boise',
	'America/Buenos_Aires',
	'America/Cambridge_Bay',
	'America/Campo_Grande',
	'America/Cancun',
	'America/Caracas',
	'America/Catamarca',
	'America/Cayenne',
	'America/Cayman',
	'America/Chicago',
	'America/Chihuahua',
	'America/Ciudad_Juarez',
	'America/Coral_Harbour',
	'America/Cordoba',
	'America/Costa_Rica',
	'America/Creston',
	'America/Cuiaba',
	'America/Curacao',
	'America/Danmarkshavn',
	'America/Dawson',
	'America/Dawson_Creek',
	'America/Denver',
	'America/Detroit',
	'America/Dominica',
	'America/Edmonton',
	'America/Eirunepe',
	'America/El_Salvador',
	'America/Ensenada',
	'America/Fort_Nelson',
	'America/Fort_Wayne',
	'America/Fortaleza',
	'America/Glace_Bay',
	'America/Godthab',
	'America/Goose_Bay',
	'America/Grand_Turk',
	'America/Grenada',
	'America/Guadeloupe',
	'America/Guatemala',
	'America/Guayaquil',
	'America/Guyana',
	'America/Halifax',
	'America/Havana',
	'America/Hermosillo',
	'America/Indiana/Indianapolis',
	'America/Indiana/Knox',
	'America/Indiana/Marengo',
	'America/Indiana/Petersburg',
	'America/Indiana/Tell_City',
	'America/Indiana/Vevay',
	'America/Indiana/Vincennes',
	'America/Indiana/Winamac',
	'America/Indianapolis',
	'America/Inuvik',
	'America/Iqaluit',
	'America/Jamaica',
	'America/Jujuy',
	'America/Juneau',
	'America/Kentucky/Louisville',
	'America/Kentucky/Monticello',
	'America/Knox_IN',
	'America/Kralendijk',
	'America/La_Paz',
	'America/Lima',
	'America/Los_Angeles',
	'America/Louisville',
	'America/Lower_Princes',
	'America/Maceio',
	'America/Managua',
	'America/Manaus',
	'America/Marigot',
	'America/Martinique',
	'America/Matamoros',
	'America/Mazatlan',
	'America/Mendoza',
	'America/Menominee',
	'America/Merida',
	'America/Metlakatla',
	'America/Mexico_City',
	'America/Miquelon',
	'America/Moncton',
	'America/Monterrey',
	'America/Montevideo',
	'America/Montreal',
	'America/Montserrat',
	'America/Nassau',
	'America/New_York',
	'America/Nipigon',
	'America/Nome',
	'America/Noronha',
	'America/North_Dakota/Beulah',
	'America/North_Dakota/Center',
	'America/North_Dakota/New_Salem',
	'America/Nuuk',
	'America/Ojinaga',
	'America/Panama',
	'America/Pangnirtung',
	'America/Paramaribo',
	'America/Phoenix',
	'America/Port-au-Prince',
	'America/Port_of_Spain',
	'America/Porto_Acre',
	'America/Porto_Velho',
	'America/Puerto_Rico',
	'America/Punta_Arenas',
	'America/Rainy_River',
	'America/Rankin_Inlet',
	'America/Recife',
	'America/Regina',
	'America/Resolute',
	'America/Rio_Branco',
	'America/Rosario',
	'America/Santa_Isabel',
	'America/Santarem',
	'America/Santiago',
	'America/Santo_Domingo',
	'America/Sao_Paulo',
	'America/Scoresbysund',
	'America/Shiprock',
	'America/Sitka',
	'America/St_Barthelemy',
	'America/St_Johns',
	'America/St_Kitts',
	'America/St_Lucia',
	'America/St_Thomas',
	'America/St_Vincent',
	'America/Swift_Current',
	'America/Tegucigalpa',
	'America/Thule',
	'America/Thunder_Bay',
	'America/Tijuana',
	'America/Toronto',
	'America/Tortola',
	'America/Vancouver',
	'America/Virgin',
	'America/Whitehorse',
	'America/Winnipeg',
	'America/Yakutat',
	'America/Yellowknife',
	'Antarctica/Casey',
	'Antarctica/Davis',
	'Antarctica/DumontDUrville',
	'Antarctica/Macquarie',
	'Antarctica/Mawson',
	'Antarctica/McMurdo',
	'Antarctica/Palmer',
	'Antarctica/Rothera',
	'Antarctica/South_Pole',
	'Antarctica/Syowa',
	'Antarctica/Troll',
	'Antarctica/Vostok',
	'Arctic/Longyearbyen',
	'Asia/Aden',
	'Asia/Almaty',
	'Asia/Amman',
	'Asia/Anadyr',
	'Asia/Aqtau',
	'Asia/Aqtobe',
	'Asia/Ashgabat',
	'Asia/Ashkhabad',
	'Asia/Atyrau',
	'Asia/Baghdad',
	'Asia/Bahrain',
	'Asia/Baku',
	'Asia/Bangkok',
	'Asia/Barnaul',
	'Asia/Beirut',
	'Asia/Bishkek',
	'Asia/Brunei',
	'Asia/Calcutta',
	'Asia/Chita',
	'Asia/Choibalsan',
	'Asia/Chongqing',
	'Asia/Chungking',
	'Asia/Colombo',
	'Asia/Dacca',
	'Asia/Damascus',
	'Asia/Dhaka',
	'Asia/Dili',
	'Asia/Dubai',
	'Asia/Dushanbe',
	'Asia/Famagusta',
	'Asia/Gaza',
	'Asia/Harbin',
	'Asia/Hebron',
	'Asia/Ho_Chi_Minh',
	'Asia/Hong_Kong',
	'Asia/Hovd',
	'Asia/Irkutsk',
	'Asia/Istanbul',
	'Asia/Jakarta',
	'Asia/Jayapura',
	'Asia/Jerusalem',
	'Asia/Kabul',
	'Asia/Kamchatka',
	'Asia/Karachi',
	'Asia/Kashgar',
	'Asia/Kathmandu',
	'Asia/Katmandu',
	'Asia/Khandyga',
	'Asia/Kolkata',
	'Asia/Krasnoyarsk',
	'Asia/Kuala_Lumpur',
	'Asia/Kuching',
	'Asia/Kuwait',
	'Asia/Macao',
	'Asia/Macau',
	'Asia/Magadan',
	'Asia/Makassar',
	'Asia/Manila',
	'Asia/Muscat',
	'Asia/Nicosia',
	'Asia/Novokuznetsk',
	'Asia/Novosibirsk',
	'Asia/Omsk',
	'Asia/Oral',
	'Asia/Phnom_Penh',
	'Asia/Pontianak',
	'Asia/Pyongyang',
	'Asia/Qatar',
	'Asia/Qostanay',
	'Asia/Qyzylorda',
	'Asia/Rangoon',
	'Asia/Riyadh',
	'Asia/Saigon',
	'Asia/Sakhalin',
	'Asia/Samarkand',
	'Asia/Seoul',
	'Asia/Shanghai',
	'Asia/Singapore',
	'Asia/Srednekolymsk',
	'Asia/Taipei',
	'Asia/Tashkent',
	'Asia/Tbilisi',
	'Asia/Tehran',
	'Asia/Tel_Aviv',
	'Asia/Thimbu',
	'Asia/Thimphu',
	'Asia/Tokyo',
	'Asia/Tomsk',
	'Asia/Ujung_Pandang',
	'Asia/Ulaanbaatar',
	'Asia/Ulan_Bator',
	'Asia/Urumqi',
	'Asia/Ust-Nera',
	'Asia/Vientiane',
	'Asia/Vladivostok',
	'Asia/Yakutsk',
	'Asia/Yangon',
	'Asia/Yekaterinburg',
	'Asia/Yerevan',
	'Atlantic/Azores',
	'Atlantic/Bermuda',
	'Atlantic/Canary',
	'Atlantic/Cape_Verde',
	'Atlantic/Faeroe',
	'Atlantic/Faroe',
	'Atlantic/Jan_Mayen',
	'Atlantic/Madeira',
	'Atlantic/Reykjavik',
	'Atlantic/South_Georgia',
	'Atlantic/St_Helena',
	'Atlantic/Stanley',
	'Australia/ACT',
	'Australia/Adelaide',
	'Australia/Brisbane',
	'Australia/Broken_Hill',
	'Australia/Canberra',
	'Australia/Currie',
	'Australia/Darwin',
	'Australia/Eucla',
	'Australia/Hobart',
	'Australia/LHI',
	'Australia/Lindeman',
	'Australia/Lord_Howe',
	'Australia/Melbourne',
	'Australia/NSW',
	'Australia/North',
	'Australia/Perth',
	'Australia/Queensland',
	'Australia/South',
	'Australia/Sydney',
	'Australia/Tasmania',
	'Australia/Victoria',
	'Australia/West',
	'Australia/Yancowinna',
	'Brazil/Acre',
	'Brazil/DeNoronha',
	'Brazil/East',
	'Brazil/West',
	'CET',
	'CST6CDT',
	'Canada/Atlantic',
	'Canada/Central',
	'Canada/Eastern',
	'Canada/Mountain',
	'Canada/Newfoundland',
	'Canada/Pacific',
	'Canada/Saskatchewan',
	'Canada/Yukon',
	'Chile/Continental',
	'Chile/EasterIsland',
	'Cuba',
	'EET',
	'EST',
	'EST5EDT',
	'Egypt',
	'Eire',
	'Etc/GMT',
	'Etc/GMT+0',
	'Etc/GMT+1',
	'Etc/GMT+10',
	'Etc/GMT+11',
	'Etc/GMT+12',
	'Etc/GMT+2',
	'Etc/GMT+3',
	'Etc/GMT+4',
	'Etc/GMT+5',
	'Etc/GMT+6',
	'Etc/GMT+7',
	'Etc/GMT+8',
	'Etc/GMT+9',
	'Etc/GMT-0',
	'Etc/GMT-1',
	'Etc/GMT-10',
	'Etc/GMT-11',
	'Etc/GMT-12',
	'Etc/GMT-13',
	'Etc/GMT-14',
	'Etc/GMT-2',
	'Etc/GMT-3',
	'Etc/GMT-4',
	'Etc/GMT-5',
	'Etc/GMT-6',
	'Etc/GMT-7',
	'Etc/GMT-8',
	'Etc/GMT-9',
	'Etc/GMT0',
	'Etc/Greenwich',
	'Etc/UCT',
	'Etc/UTC',
	'Etc/Universal',
	'Etc/Zulu',
	'Europe/Amsterdam',
	'Europe/Andorra',
	'Europe/Astrakhan',
	'Europe/Athens',
	'Europe/Belfast',
	'Europe/Belgrade',
	'Europe/Berlin',
	'Europe/Bratislava',
	'Europe/Brussels',
	'Europe/Bucharest',
	'Europe/Budapest',
	'Europe/Busingen',
	'Europe/Chisinau',
	'Europe/Copenhagen',
	'Europe/Dublin',
	'Europe/Gibraltar',
	'Europe/Guernsey',
	'Europe/Helsinki',
	'Europe/Isle_of_Man',
	'Europe/Istanbul',
	'Europe/Jersey',
	'Europe/Kaliningrad',
	'Europe/Kiev',
	'Europe/Kirov',
	'Europe/Kyiv',
	'Europe/Lisbon',
	'Europe/Ljubljana',
	'Europe/London',
	'Europe/Luxembourg',
	'Europe/Madrid',
	'Europe/Malta',
	'Europe/Mariehamn',
	'Europe/Minsk',
	'Europe/Monaco',
	'Europe/Moscow',
	'Europe/Nicosia',
	'Europe/Oslo',
	'Europe/Paris',
	'Europe/Podgorica',
	'Europe/Prague',
	'Europe/Riga',
	'Europe/Rome',
	'Europe/Samara',
	'Europe/San_Marino',
	'Europe/Sarajevo',
	'Europe/Saratov',
	'Europe/Simferopol',
	'Europe/Skopje',
	'Europe/Sofia',
	'Europe/Stockholm',
	'Europe/Tallinn',
	'Europe/Tirane',
	'Europe/Tiraspol',
	'Europe/Ulyanovsk',
	'Europe/Uzhgorod',
	'Europe/Vaduz',
	'Europe/Vatican',
	'Europe/Vienna',
	'Europe/Vilnius',
	'Europe/Volgograd',
	'Europe/Warsaw',
	'Europe/Zagreb',
	'Europe/Zaporozhye',
	'Europe/Zurich',
	'GB',
	'GB-Eire',
	'GMT',
	'GMT+0',
	'GMT-0',
	'GMT0',
	'Greenwich',
	'HST',
	'Hongkong',
	'Iceland',
	'Indian/Antananarivo',
	'Indian/Chagos',
	'Indian/Christmas',
	'Indian/Cocos',
	'Indian/Comoro',
	'Indian/Kerguelen',
	'Indian/Mahe',
	'Indian/Maldives',
	'Indian/Mauritius',
	'Indian/Mayotte',
	'Indian/Reunion',
	'Iran',
	'Israel',
	'Jamaica',
	'Japan',
	'Kwajalein',
	'Libya',
	'MET',
	'MST',
	'MST7MDT',
	'Mexico/BajaNorte',
	'Mexico/BajaSur',
	'Mexico/General',
	'NZ',
	'NZ-CHAT',
	'Navajo',
	'PRC',
	'PST8PDT',
	'Pacific/Apia',
	'Pacific/Auckland',
	'Pacific/Bougainville',
	'Pacific/Chatham',
	'Pacific/Chuuk',
	'Pacific/Easter',
	'Pacific/Efate',
	'Pacific/Enderbury',
	'Pacific/Fakaofo',
	'Pacific/Fiji',
	'Pacific/Funafuti',
	'Pacific/Galapagos',
	'Pacific/Gambier',
	'Pacific/Guadalcanal',
	'Pacific/Guam',
	'Pacific/Honolulu',
	'Pacific/Johnston',
	'Pacific/Kanton',
	'Pacific/Kiritimati',
	'Pacific/Kosrae',
	'Pacific/Kwajalein',
	'Pacific/Majuro',
	'Pacific/Marquesas',
	'Pacific/Midway',
	'Pacific/Nauru',
	'Pacific/Niue',
	'Pacific/Norfolk',
	'Pacific/Noumea',
	'Pacific/Pago_Pago',
	'Pacific/Palau',
	'Pacific/Pitcairn',
	'Pacific/Pohnpei',
	'Pacific/Ponape',
	'Pacific/Port_Moresby',
	'Pacific/Rarotonga',
	'Pacific/Saipan',
	'Pacific/Samoa',
	'Pacific/Tahiti',
	'Pacific/Tarawa',
	'Pacific/Tongatapu',
	'Pacific/Truk',
	'Pacific/Wake',
	'Pacific/Wallis',
	'Pacific/Yap',
	'Poland',
	'Portugal',
	'ROC',
	'ROK',
	'Singapore',
	'Turkey',
	'UCT',
	'US/Alaska',
	'US/Aleutian',
	'US/Arizona',
	'US/Central',
	'US/East-Indiana',
	'US/Eastern',
	'US/Hawaii',
	'US/Indiana-Starke',
	'US/Michigan',
	'US/Mountain',
	'US/Pacific',
	'US/Samoa',
	'UTC',
	'Universal',
	'W-SU',
	'WET',
	'Zulu',
];

export const INTERVALS = {
	'1min': 60,
	'2min': 2 * 60,
	'3min': 3 * 60,
	'5min': 5 * 60,
	'10min': 10 * 60,
	'15min': 15 * 60,
	'30min': 30 * 60,
	'1hr': 60 * 60,
	'2hr': 2 * 60 * 60,
	'1day': 24 * 60 * 60,
	'1week': 7 * 24 * 60 * 60,
	'1month': 30 * 24 * 60 * 60,
	'1year': 365 * 24 * 60 * 60,
	// Add additional intervals as needed
};
